# Generated by Django 4.0.6 on 2023-04-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
