# Generated by Django 4.0.6 on 2023-04-28 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_problem_memory_limit_alter_problem_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='problem',
            name='num_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='num_solves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
