# Generated by Django 4.0.6 on 2023-04-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_problem_created_problem_num_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcategory',
            name='code',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
