# Generated by Django 4.0.6 on 2023-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_problemcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
