# Generated by Django 4.0.6 on 2023-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
