# Generated by Django 4.0.6 on 2023-04-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_problem_code_alter_problemcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcategory',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
